services:
  api:
    build:
      target: dev
    volumes:
      - ./app:/app/app
      - ./alembic:/app/alembic
      - ./tests:/app/tests
      - ./htmlcov:/app/htmlcov

    ports:
      - 8000:8000

  postgres:
    ports:
      - 5432:5432

  redis:
    ports:
      - 6379:6379
